{{- if (not .Values.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins-scripts.fullname" . }}
  labels:
    {{- include "jenkins-scripts.labels" . | nindent 4 }}
type: Opaque
data:
  jupiteroneAccountId: {{ default "" .Values.secrets.jupiteroneAccountId | b64enc | quote }}
  jupiteroneApiKey: {{ default "" .Values.secrets.jupiteroneApiKey | b64enc | quote }}
  jenkinsURL: {{ default "" .Values.secrets.jenkinsURL | b64enc | quote }}
  jenkinsUser: {{ default "" .Values.secrets.jenkinsUser | b64enc | quote }}
  jenkinsPassword: {{ default "" .Values.secrets.jenkinsPassword | b64enc | quote }}
{{- end }}